server:
    servlet:
        context-path: /api
    error:
        include-message: always
spring:
    jackson:
        default-property-inclusion: non_null
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
    datasource:
        url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
        driverClassName: org.h2.Driver
        username: admin
        password: admin
        dbcp2:
            test-while-idle: true
            validation-query: SELECT 1
    h2:
        console:
            # http://localhost:8080/api/h2-console
            # username: admin
            # password: admin
            enabled: true
            settings:
                web-allow-others: true

